# Generated by Django 5.1.2 on 2025-03-20 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
