# Generated by Django 5.1.2 on 2025-03-21 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_course_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='creator',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
