# Generated by Django 5.1.2 on 2025-04-07 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_answer_feedback_answer_open_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='open_answer',
        ),
        migrations.AlterField(
            model_name='answer',
            name='selected_choices',
            field=models.ManyToManyField(to='exams.choice'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single', 'Single Choice'), ('multiple', 'Multiple Choice')], max_length=10),
        ),
    ]
