# Generated by Django 5.1.2 on 2025-03-26 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='file_type',
            field=models.CharField(max_length=255),
        ),
    ]
