# Generated by Django 5.1.2 on 2025-04-02 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_assignment_support_file_assignment_support_file_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='support_file',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='support_file_name',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='support_file_type',
        ),
    ]
