# Generated by Django 5.1.2 on 2025-04-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0010_remove_assignment_support_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='support_file',
            field=models.FileField(blank=True, null=True, upload_to='assignment_support/'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='support_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='support_file_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
